<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo LBL_TT_SITE; ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="<?php echo ST_PT_VENDOR; ?>css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo ST_PT_VENDOR; ?>css/bootstrap-formhelpers.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
    <style> body { padding-top: 50px; padding-bottom: 20px; } </style>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="<?php echo BASEURL; ?>index.php" class="navbar-brand"><?php echo LBL_HE_TITLE; ?></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul id="navbar_menu" class="nav navbar-nav">          
            <li class="active"><a href="?controle=Contact&acao=contactList"><?php echo LBL_HE_ME_CO; ?></a></li>
            <li><a href="?controle=Dashboard&acao=render"><?php echo LBL_HE_ME_DA; ?></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="about.php">Sobre</a></li>
          </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <main class="container">