		
	</main> <!-- /container -->

	<hr>
	<footer class="container">
		<p>&copy; 2018 - Bruno Zani</p>
	</footer>

	<script src="<?php echo BASEURL;?>js/jquery.min.js"></script>
	<script src="<?php echo ST_PT_VENDOR; ?>js/bootstrap.min.js"></script>
	<script src="<?php echo ST_PT_VENDOR; ?>js/bootstrap-formhelpers.min.js"></script>
	<script src="<?php echo ST_PT_VENDOR; ?>js/mdb.min.js"></script>
	<script src="js/template.js"></script>
</body>
</html>